config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shops
  root 'top#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_one_attached :image
  validates :store_name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :open_hour, presence: true
  validates :map_url, presence: true
  validates :caption, presence: true
  validate :image_check

  def image_check
    if image.present?
      unless image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:image, 'にはjpegまたはpngファイルを添付してください')
      end
    else
      unless image.attached?
        errors.add(:image, 'ファイルを添付してください')
      end
    end
  end  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true,   length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  before_action :set_search

  def set_search
    @q = Shop.ransack(params[:q])
    @shops = @q.result
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
before_action :set_shop, only: [ :show, :edit, :update, :destroy]
  def index
    @shops = Shop.all
    @shops = Shop.page(params[:page])
    @q = Shop.ransack(params[:q])
    @shops = @q.result
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to @shop, notice: "店舗情報を登録しました。"
    else
      @shops = Shop.page(params[:page]).per(16)
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to @shop, notice: "店舗情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path, notice: "店舗情報を削除しました。"
  end

  private
  def shop_params
    params.require(:shop).permit(:store_name, :address, :phone_number, :open_hour, :image, :map_url, :caption)
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController

  layout 'index'
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tofu2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>
    <div class="container mb-5">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/layouts/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tofu</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   

  <body>
    <%# <div class="container mb-5">  %>
    <%= yield %>
    <%# </div> %>
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom justify-content-center">
  <%# <div class="container"> %>
    <%# <a class="navbar-brand" href="/">Topページへ戻る</a> %>
  <ul class="nav">
    <li class="nav-item">
      <a class="nav-link" href="/shops"><i class="fas fa-store-alt fa-2x"></i></a>
    </li>
    <li class="nav-item">
      <%= link_to new_shop_path, class: "nav-link" do %>
        <i class="fas fa-plus-square fa-2x"></i>
      <% end %>
    </li>
      <li class="nav-item">
      <% if user_signed_in? %>
        <%= link_to edit_user_registration_path, class: "nav-link" do %>
          <i class="fas fa-smile fa-2x"></i>
        <% end %>
      <% else %>
        <%= link_to new_user_session_path, class: "nav-link" do %>
          <i class="fas fa-smile fa-2x"></i>
        <% end %>
      <% end %>
      </li>
  </ul>
  </div>
</nav>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
    <b><a class="navbar-brand" href="/shops">TOFU.HUB</a></b>
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
    </ul>

    <% if user_signed_in? %>
      <%= link_to edit_user_registration_path, class: "nav-item" do %>
        <i class="fas fa-smile fa-2x mr-4 "></i>
      <% end %>
    <% else %>
      <%= link_to new_user_session_path, class: "nav-item" do %>
        <i class="fas fa-smile fa-2x mr-4 "></i>
      <% end %>
    <% end %>
    
    <%= search_form_for @q ,class: "nav-item form-inline mb-2 mb-lg-0" do |f| %>
      <%= f.search_field :store_name_or_address_cont, class: "form-control mr-sm-2", placeholder: "キーワードで検索" %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
</nav>

app/views/shops/_form.html.erb
<%= render "shared/errors", obj: shop %>
<%= form_with model: shop, local:true do |f| %>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :store_name %>
    <%= f.text_field :store_name, class: "form-control", placeholder: "店舗名を入れてください" %>
  </div>
  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: "form-control", placeholder: "住所を入れてください"%>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: "form-control", placeholder: "電話番号を入れてください" %>
  </div>
  <div class="form-group">
    <%= f.label :open_hour %>
    <%= f.text_field :open_hour, class: "form-control", placeholder: "営業時間を入れてください(例8:00~17:00)" %>
  </div>
  <div class="form-group">
    <%= f.label :caption %>
    <%= f.text_area :caption, class: "form-control", placeholder: "お店の一言情報を入れてください" %>
  </div>
  <div class="form-group">
    <%= f.label :map_url %>
    <%= f.text_area :map_url, class: "form-control", placeholder: "googlemapのURLを入れてください" %>
  </div>
  <p>
    <%= f.submit t(".shop"), class: "btn btn-block btn-primary" %>
  </p>
  <p>
    <%= link_to t(".back"), :back, class: "btn btn-block btn-secondary" %>
  </p>
<% end %>

app/views/shops/edit.html.erb
<div class="row">
  <div class="col-lg-8 mx-auto">
    <div class="logo col-lg-12 mb-3 text-center">
      <h1>Edit Post</h1>
    </div>

    <div class="card">
      <div class="row no-gutters">
        <div class="col-lg-6">
          <% if @shop.image.attached? %>
            <%= image_tag @shop.image.variant(resize_to_fill: [800, 800]).processed, class: "card-img" %>
          <% else %>
            <%= image_tag "no_image", class: "card-img" %>
          <% end %>
        </div>

        <div class="col-lg-6 card-cody">
          <%= render "form", shop: @shop %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shops/index.html.erb
<div class="container">
  <div class="row">
    <% @shops.each do |shop| %>
      <div class="card text-dark bg-color border-dark mb-4 mr-1" style="width: 14rem;" >
        <%= link_to shop do %>
          <% if shop.image.attached? %>
            <%= image_tag shop.image.variant(resize_to_fill: [400, 400]).processed, class: "card-img" %>
          <% else %>
            <%= image_tag "no_image", class: "card-img" %>
          <% end %>
        <% end %>
        <div class="card-body">
          <div class="card-title">
            <p><b><%= shop.store_name %></b></p>
            <p class="card-text"><%= shop.caption %></p>
          </div>
        <!--<h5><%= link_to "Go Tofu »", shop, class: "" %></h5>-->
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shops/new.html.erb
<div class="col-lg-6 mx-auto">
  <div class="logo mb-3 text-center">
    <h1><%= t ".title" %></h1>
  </div>
  <%= render "form", shop: @shop %>
</div>

app/views/shops/show.html.erb
<div class="col-lg-6 mx-auto">
<div class="row">
  <div class="col-lg-12 mx-auto">
    <%= image_tag @shop.image.variant(resize_to_fill: [500, 500]).processed, class: "d-block mx-auto" %>
  </div>
</div>

<div class="col-lg-12">
  <div class="font-c">
  <p><b>店舗名：<%= @shop.store_name %></b></p>

  <p><b>住所：<%= @shop.address %></b></p>

  <p><b>電話番号：<%= @shop.phone_number %></b></p>

  <p><b>営業時間：<%= @shop.open_hour %></b></p>

  <p><b>一言コメント:<%= @shop.caption %></b></p>
  </div>

  <iframe src=<%= @shop.map_url %> width="510" height="450" frameborder="0" style="border:0;" alloΩΩwfullscreen="" aria-hidden="false" tabindex="0"></iframe>

    <p>
      <%= link_to t(".edit"), edit_shop_path(@shop), method: :get, class: "btn btn-block btn-primary" %>
    </p>
    <p>
      <%= button_tag t(".delete"), class: "btn btn-block btn-warning", data: { toggle: "modal", target: "#delete-shop" } %>
    </p>
  </div>
</div>
</div>

<div class="modal fade" id="delete-shop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">投稿削除</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= image_tag @shop.image.variant(resize_to_fill: [800, 800]).processed, class: "img-fluid" %></p>
        <p><%= "投稿を削除しますか？" %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">キャンセル</button>
        <%= link_to "削除", shop_path(@shop), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>

app/views/top/index.html.erb
<div class="jumbotron jumbotron-extend m-0">
      <div class="container-fluid jumbotron-container">
        <h1 class="text-light">TOFU.HUB</h1>
        <h2 class="text-light">あなたに最高の豆腐を</h2>
        <%# <a class="btn btn-primary btn-lg" href="#" role="button">Learn more </a> %>
<ul class="nav">
    <li class="nav-item">
      <%= link_to shops_path, class: "nav-link" do %>
        <%# <button class="btn btn-link btn-lg">Learn more »</button> %>
        <h2><%= link_to "Go Tofu »", shops_path, class: "text-white kasen border-h" %></h2>
      <% end %>
    </li>
  </ul>
  </div>
</div>